name: Deploy website to KTH virtual server

env:
  WC_HUGO_VERSION: "0.135.0"

on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Hugo
        uses: peaceiris/actions-hugo@v3
        with:
          hugo-version: ${{ env.WC_HUGO_VERSION }}
          extended: true

      - name: Build site with Hugo
        env:
          HUGO_ENVIRONMENT: production
        run: hugo --minify

      - name: Copy site to KTH server via SSH
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "public/*"
          target: ${{ secrets.SSH_TARGET_DIR }}
